kube-prometheus-stack:
  grafana:
    additionalDataSources:
      - name: Loki
        type: loki
        access: proxy
        url: http://pronunt-loki.pronunt-monitoring-test-ns.svc.cluster.local:3100
        isDefault: false
        jsonData:
          maxLines: 1000
          timeout: 60
        editable: true

httpRoute:
  gateway:
    name: pronunt-gateway-test
    namespace: pronunt-gateway-test-ns
  hostname: grafana.pronunt.com
