{{- if .Values.environment.includeProd }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
{{ toYaml .Values.gateway.listeners | indent 4 }}
{{- end }}
{{- if .Values.environment.includeTest }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.testGateway.name }}
  namespace: {{ .Values.testGateway.namespace }}
spec:
  gatewayClassName: {{ .Values.testGateway.gatewayClassName }}
  listeners:
{{ toYaml .Values.testGateway.listeners | indent 4 }}
{{- end }}
