{{- if .Values.environment.includeProd }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.app.name }}
  labels:
{{ toYaml .Values.namespaces.app.labels | indent 4 }}
{{- end }}
{{- if and .Values.environment.includeProd .Values.environment.includeTest }}
---
{{- end }}
{{- if .Values.environment.includeTest }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.appTest.name }}
  labels:
{{ toYaml .Values.namespaces.appTest.labels | indent 4 }}
{{- end }}
{{- if and .Values.environment.includeProd .Values.environment.includeTest }}
---
{{- end }}
{{- if .Values.environment.includeProd }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.gateway.name }}
{{- if .Values.namespaces.gateway.labels }}
  labels:
{{ toYaml .Values.namespaces.gateway.labels | indent 4 }}
{{- end }}
{{- end }}
{{- if and .Values.environment.includeProd .Values.environment.includeTest }}
---
{{- end }}
{{- if .Values.environment.includeTest }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.gatewayTest.name }}
{{- if .Values.namespaces.gatewayTest.labels }}
  labels:
{{ toYaml .Values.namespaces.gatewayTest.labels | indent 4 }}
{{- end }}
{{- end }}
{{- if and .Values.environment.includeProd .Values.environment.includeTest }}
---
{{- end }}
{{- if .Values.environment.includeProd }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.aiInfra.name }}
{{- if .Values.namespaces.aiInfra.labels }}
  labels:
{{ toYaml .Values.namespaces.aiInfra.labels | indent 4 }}
{{- end }}
{{- end }}
{{- if and .Values.environment.includeProd .Values.environment.includeTest }}
---
{{- end }}
{{- if .Values.environment.includeTest }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.aiInfraTest.name }}
{{- if .Values.namespaces.aiInfraTest.labels }}
  labels:
{{ toYaml .Values.namespaces.aiInfraTest.labels | indent 4 }}
{{- end }}
{{- end }}
{{- if .Values.environment.includeProd }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.monitoring.name }}
{{- if .Values.namespaces.monitoring.labels }}
  labels:
{{ toYaml .Values.namespaces.monitoring.labels | indent 4 }}
{{- end }}
{{- end }}
