namespace:
  name: pronunt-ai-infra-test-ns

persistence:
  size: 20Gi

resources:
  requests:
    cpu: "2"
    memory: 8Gi
    nvidia.com/gpu: "1"
  limits:
    cpu: "4"
    memory: 16Gi
    nvidia.com/gpu: "1"
