image:
  tag: d5178f3
nodeSelector:
  accelerator: nvidia
tolerations:
  - key: gpu
    operator: Equal
    value: "true"
    effect: NoSchedule
env:
  config:
    APP_ENV: test
    INHOUSE_BASE_URL: http://pronunt-ollama.pronunt-ai-infra-test-ns.svc.cluster.local:11434
namespace:
  name: pronunt-app-test-ns
httpRoute:
  enabled: true
  hostnames:
    - test.pronunt.com
  parentRefs:
    - name: pronunt-gateway-test
      namespace: pronunt-gateway-test-ns
  pathPrefix: /api/v1/ai
