image:
  tag: b4be554
env:
  config:
    APP_ENV: test
    GITHUB_OAUTH_CLIENT_ID: Ov23lil9XGjoKXXCTcXj
    GITHUB_OAUTH_REDIRECT_URI: https://pronunt.com/api/v1/auth/github/callback
    FRONTEND_AUTH_SUCCESS_URL: https://pronunt.com/connect
    FRONTEND_AUTH_FAILURE_URL: https://pronunt.com/connect
namespace:
  name: pronunt-app-test-ns
httpRoute:
  enabled: true
  hostnames:
    - pronunt.com
  parentRefs:
    - name: pronunt-gateway-test
      namespace: pronunt-gateway-test-ns
  pathPrefix: /api/v1/auth
