---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pronunt-ingestion-service-secret
  namespace: pronunt-app-ns
spec:
  encryptedData:
    INTERNAL_SERVICE_TOKEN: AgCDsQ8yepQQxxHLBrp1NagWA3XoJHtRsRwBhrRYjLw+ZRAfjiXqh33/tXBiRyeSk+Djg5yLb8tffDpwctdZMrzlcpbQFwspvxJ1IAL94DURZpQypQZlYtjIcP+t92Ee5GtCwrdubiEVm49x37JBzEMrqNWH7JV6uu7DAANo9guqZI3pSoRJZ4RXImSDCvLwfP/cZj5X306KGTnZZqk7augbcsgRfisHDGBd5TuVJDTHRiBpScXKr2+O7YgyZ8XtksRrRICGafj7u3l6MHsGOD/n4LSfZVS2/NpYQ5fuPUBnx1mxzN1b/j7hv+05eWD94/1qS5It3wIJtb/G1kNg1fzsRPOgLyQv7P/60lbeM9W07xLIVUNlee5Jlbc56od0MjgKwsuQ2c93Fv4QHRS2G4xiEJeaeXPGQJIm8CLz+IMAjTc+7XvLKmpTy70Del8yamkjb5D+Vn19++An8UpUmt5FKwjiIFeEi4DkVksyeozIV13d+V300/gWPNxCJElZrpCx9ULICnZHvTduJz40sUcBVUrarP/iTEFZVk6iMPH4X6LDoJ2hpoId6cEEbTWbos95PuqNeQp7/yg/ZvUPC6c8i6dHpc+/j+Sx9WyeGWHiJGp3jDiKDyNyRvVmu2BSpqGMx7KtFgZw/Fz+vDDfQpr+HgKEk+092goEtxpocTMrdTbuip2Lz7DOFIZxUWX28GLaYIqy3j0qNfn+dY8KDM3c4h9KYzzDXHEk5JhDzrX0CVdWFVKh3E7qWxKHPxdDn0Cvli1R26dVcfs7WatLxeyx
  template:
    metadata:
      name: pronunt-ingestion-service-secret
      namespace: pronunt-app-ns
    type: Opaque
