---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pronunt-worker-service-secret
  namespace: pronunt-app-ns
spec:
  encryptedData:
    WORKER_AUTH_TOKEN: AgCQZpxSPxd9LIKwFSuNBjeYcNdpvwIs66d7WmELILvBnw+3k9ayqZ5D5ufCgmkvfgTCDsw2Kq/bIpKOVvaxluXIGcI74dqg0fJ22ZnAVH3YzWMxPY2DCZnRGimNf1ADsV+eSbSVq2c3pYulsCr4ycG9pE9qRkadzqdDsRy79zHTC20rZEarYgTUvhb+8i97Ge8Sznck12z3HC/AHswboqFwuvuVW7DtGiLT4+oFc9X74Nwqoxe/NSF5q0morIxW1SZXLuaEu1EBMuuB92wQ7lhFAMNrB+a4vC+wI9zlPtZ/dHiJAqSaYXqssjrlLursB61Z/xwmUsqOsYl9lt64nItYTKOOwiijF9kMLywwlw7Tn4GgcQFtr+uRUUpbzz+fZEaAuqwKwOGsZzcKz3CwTBNmCBbJP3arcVKWUJSi7z9BHd9UwYt9+CLIzG0d5/y5vp1gq/sfTkOLaUINDER+uAedodLXgfsPbNQBx9BhTaYqbElGg9tkzxQmKmoxBMD1HlC5Xiv82JeuARItkA+IryGwqBqX7AzHoAlo2GLH+p4rkylXVbAOngX0WAkXNNi3IsVU8v8TRN2iYy9h8TfwGVe5NdYo2HS9umuspXdmPpY09Lk+Baok2EugzlWaqUtyy7y0FgwT5PTvnLjN90NEixiDWK2E4jo4hncq/zJr24CoOB70JI8N9Jj1FlryL1TChWE+toSaKtLh4C7VX9Ya0AV78NqF88/fTLoEV78FdBN5FFl/+0LnM3iK8+rDKHN5VFbVtbboAk0DOFmsJMebMZQ=
  template:
    metadata:
      name: pronunt-worker-service-secret
      namespace: pronunt-app-ns
    type: Opaque
