---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pronunt-frontend-service-secret
  namespace: pronunt-app-ns
spec:
  encryptedData:
    FRONTEND_SESSION_SECRET: AgC/cIJkmo5Gfo2gpNZ3UaCoJCVBEkGfu2QLApKvpimP5gCh1U3J4Ad3JhxsmE+Dh0V4u6a8jR9/TAjRxws31zyt6EplY6C89YFQxAFk2J/iE8VPuRd7csvfTM+do6Y8VlNCPQkt7dkAa8tWbeWqw9XRS/ISbWc0qvITD959Du3keKweF9sEhExcflBlcdtqMNRTckO5rAC07nBqzCv1d8900UzYQJdx1NgxBx/RBlFtzzbPiaMCAnqWRGyXJqh9uvbCxC7FVj9rKqwCQMagJLm+vQWkj65ks25T46B3SrmATBS7U7XslG4pC51k4ToinCno1UrygI6aINZEBzi3SjWaGKSyA5+WT0ZHCeAfaM7ZOXfjc/AxTmA3hrY9hCdIogSmkIaaVeMvH7CBsrMneH3rkYXR9pTZsdFTsqLHNptjf+P9N7FSkmOBATVuBWXJKrGcXRVwiFuPizbuws5LLMhdyMFKTV5d0i2s5orhKPXHSWTTpG5RAo6bGU0+7hfoPzkO+GYNCDz/or0G2iZBsXEzLQDREn+Lr02Hgt9Gr5ylLel2fwojXMDTCYeGsOh+OUr2gtZqx4V6FW+ipP6QyGqMK87NfurwOp3Q9zSXEELYmlE4GD9UAKdqapCXRnF/wqBFmFq4oRSlB1V0OxtGKPC4yboykDo3VMG/oOU+6XZYgA7x2szc3sP5OCbZlNzcOJvYl+OVOIpV18tOq0EA+0RUFs1UPuYnP74rkLLKN5kkpJSCg7vaRQn5G1xt8Gv+2C23IjV0KKq460uJ8gR9SYU=
  template:
    metadata:
      name: pronunt-frontend-service-secret
      namespace: pronunt-app-ns
    type: Opaque
