---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pronunt-ai-service-secret
  namespace: pronunt-app-ns
spec:
  encryptedData:
    INTERNAL_SERVICE_TOKEN: AgAK1CfaaBJ4jFQ9WwS4Ja395ssEcKGne8hEbTdEMi6N2yUghzPc5Y07//HlZmI8Dbm63cEX9JOZToGM744QvFlMuR9wGFpJli1cUMlN8OfjY4Pa6uiF2i3040xNT07s87wTIJBRsdFGawaXdr8yQE/wx11e5Jg6iStSMwWO+eoG9sp2eMEDytQp25EF17NO6AJNk3Wo2RXkx50FifOsKO8RA41XgBNxuMCdgeA7A+iaK/lwirbANYwnMeCJ9ScoOyfNYzIwRs/oJ/NNDrfMSbx3DZSHqXv9V7zbo8NJN+FnymIfmvBnCNgY2yNabm7MC4i0BfX/ASOdW9xF42xHKkDnhgNFC4+23YPQjrnZXUBRB8VXUGj11ibeC41HwzUrqEwfAaRY1V2gqn4ib/TIR3jQLDIilIbslPj0GpMS/x0J8qtaVJ1jtVJcuHrx0ez8Gu11AD62qyaFtUV/eIyBTYeNuiRqgKZLoCLTjKZyeBd6e9KoRy0jHsTBYvWRPF8dc9xEM1/T2ISOUeFQ0Pn2avu1LuaoaMGcKDxIbV4Zc36QhAeTAOs59H529NVJkss1V3RuP9mklmyucej4gkB0IwC51rENCcpsNAaBqR6IzGIMyHHTaLM5fBbw16rY3mukW7XYoePt/w9hi38Mg5qQu776gFgwAeelOngJm5qfhkHCFquHm+4kNzrwXiMEJuNElg6duDcr7Gd6IrlGrXDGu+stp8euf7bYvk8q05xdpr87Ckwd45PZWcVrlJBotPe6UXDRipvClyeb6brlalhIR0JL
    OPENAI_API_KEY: AgBL5/ErL0fxE88Q5gj8g03eu5+BR8g09LlSrrEuQ4zCZciG6lVMCheRp7WwEug7D6CcnRJvCWn+38UuOBCvXRBsfHsRxwDSZrypACoO0k1Hxk6oMjUHInYg3off4hAQ/P9Y8ejI3Hw7xhWBYam13jlbYCHnXtKFBWIFy7DbH6sg0+LGrAlIfgeHv1IOWw+L/CYFnPejgsOK3ppOZI9a9SM/mWPaK8QQEgdnXARASoilx5I8PR+kpodjkDJPAs3Efgv0Wiw3rvDgDrpX2G9iy3ds2DQiJA6rUrUnNiUrikn5le2PtxuKmw42ZB5iMByGvaDyC5PJ4WVV7YtSlrFdzQN7RNiUaQD7rj1XBM0/SNJXtdL3COYAPX9R5TRPiVMRWB68ALHkXpIkocQapCfr6p43mFj7lIpiBJA6h4dRU4dywxYrq2mRvJEqeCnuP4DkI+5KcFRs2FwcoxXsLcy149wwagFS+soE18/OPrVc2y3brjwHv+p+gPMcZPouFXKc0806gifDBc+5aBjqVM0JsVBIyT9G2jv24dhxhEfb81eS6VcRCpbzG0rej5buluKCS9lZmMZgB72hDafuiGKoH60EsRJ60mmF27h4qxOAucj/s9XYHDfywu9ujdlV/jgNUYhQY/chpuijjfWQxIDeGU4iVAxdbI7TTBNm5wjlYoWvbvDeJ4mOeVjY4NSO2W/R73yY6iCUXO+5yxGl
  template:
    metadata:
      name: pronunt-ai-service-secret
      namespace: pronunt-app-ns
    type: Opaque
