apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pronunt-loki-prod
  namespace: argocd-ns
spec:
  project: pronunt
  source:
    repoURL: https://github.com/pronunt/pronunt-helm-charts.git
    targetRevision: prod
    path: infra/loki
    helm:
      releaseName: pronunt-loki
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pronunt-monitoring-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
