apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pronunt-ollama-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pronunt/pronunt-helm-charts.git
    targetRevision: prod
    path: infra/ollama
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pronunt-ai-infra-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
