apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pronunt-sealed-secrets-prod
  namespace: argocd-ns
spec:
  project: pronunt
  source:
    repoURL: https://github.com/pronunt/pronunt-helm-charts.git
    targetRevision: prod
    path: env/prod/sealed-secrets
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
