apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fullnameOverride }}-init
  namespace: {{ .Values.namespace.name }}
data:
  init-user.sh: |
    #!/bin/bash
    set -euo pipefail
    mongosh --host localhost --username "$MONGO_INITDB_ROOT_USERNAME" --password "$MONGO_INITDB_ROOT_PASSWORD" --authenticationDatabase admin <<EOF
    use ${MONGO_APP_DATABASE}
    db.createUser({
      user: "${MONGO_APP_USERNAME}",
      pwd: "${MONGO_APP_PASSWORD}",
      roles: [{ role: "readWrite", db: "${MONGO_APP_DATABASE}" }]
    })
    EOF
