{{- if .Values.secretTemplate.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fullnameOverride }}-auth
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.auth.rootUsername | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.auth.rootPassword | quote }}
  MONGO_APP_USERNAME: {{ .Values.auth.username | quote }}
  MONGO_APP_PASSWORD: {{ .Values.auth.password | quote }}
  MONGO_APP_DATABASE: {{ .Values.auth.database | quote }}
{{- end }}
