apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.fullnameOverride }}
  namespace: {{ .Values.namespace.name }}
spec:
  serviceName: {{ .Values.fullnameOverride }}-headless
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.fullnameOverride }}
  template:
    metadata:
      labels:
        app: {{ .Values.fullnameOverride }}
    spec:
      serviceAccountName: {{ if .Values.serviceAccount.name }}{{ .Values.serviceAccount.name }}{{ else }}{{ .Values.fullnameOverride }}{{ end }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- with .Values.podSecurityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
        - name: {{ .Values.fullnameOverride }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.fullnameOverride }}-auth
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          args:
            - --bind_ip_all
          securityContext:
{{ toYaml .Values.securityContext | indent 12 }}
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
            - name: mongodb-init
              mountPath: /docker-entrypoint-initdb.d/init-user.sh
              subPath: init-user.sh
          readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: mongodb-init
          configMap:
            name: {{ .Values.fullnameOverride }}-init
            defaultMode: 0755
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes:
{{ toYaml .Values.persistence.accessModes | indent 10 }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        storageClassName: {{ .Values.persistence.storageClassName }}
