apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pronunt-aggregator-service-prod
  namespace: argocd-ns
spec:
  project: pronunt
  source:
    repoURL: https://github.com/pronunt/pronunt-helm-charts.git
    targetRevision: prod
    path: apps/pronunt-aggregator-service
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pronunt-app-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
