image:
  tag: 45088b9
env:
  config:
    APP_ENV: test
namespace:
  name: pronunt-app-test-ns
httpRoute:
  enabled: true
  hostnames:
    - test.pronunt.com
  parentRefs:
    - name: pronunt-gateway-test
      namespace: pronunt-gateway-test-ns
  pathPrefix: /api/v1/aggregator
