image:
  tag: 3d2b873
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 75
namespace:
  name: pronunt-app-test-ns
httpRoute:
  enabled: true
  hostnames:
    - pronunt.com
  parentRefs:
    - name: pronunt-gateway-test
      namespace: pronunt-gateway-test-ns
  pathPrefix: /
