{{- if .Values.secretTemplate.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fullnameOverride }}-auth
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: {{ .Values.credentials.username | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.credentials.password | quote }}
  RABBITMQ_DEFAULT_VHOST: {{ .Values.credentials.vhost | quote }}
{{- end }}
