apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Values.fullnameOverride }}
  ports:
    - name: amqp
      port: {{ .Values.service.amqpPort }}
      targetPort: {{ .Values.service.amqpPort }}
    - name: management
      port: {{ .Values.service.managementPort }}
      targetPort: {{ .Values.service.managementPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}-headless
  namespace: {{ .Values.namespace.name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.fullnameOverride }}
  ports:
    - name: amqp
      port: {{ .Values.service.amqpPort }}
      targetPort: {{ .Values.service.amqpPort }}
    - name: management
      port: {{ .Values.service.managementPort }}
      targetPort: {{ .Values.service.managementPort }}
